language: go

go:
  - 1.5
  - release
  - tip

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl make git libtool build-essential dh-autoreconf pkg-config mercurial dh-autoreconf

install:
  - curl -o ./zeromq.tar.gz http://download.zeromq.org/zeromq-4.0.4.tar.gz
  - tar -C . -zxvf ./zeromq.tar.gz
  - rm ./zeromq.tar.gz
  - cd zeromq-4.0.4
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - sudo ifconfig


script:
 - go test -v . ./...
