language: go

go:
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl make git libtool build-essential dh-autoreconf pkg-config mercurial dh-autoreconf libzmq-dev

install:
  - go get github.com/nu7hatch/gouuid
  - go get gopkg.in/gcfg.v1
  - go get github.com/joernweissenborn/eventual2go
  - go get github.com/pebbe/zmq4
  - go get github.com/hashicorp/memberlist
  - go get github.com/ugorji/go/codec

script:
  - go test -v ./service/tracker/beacon ./service/peer ./service/tracker /service/manager .
  - make
